### PR TITLE
Fix Python 3.9.1 build

### PR DESCRIPTION
**Pull request by jakeloo**
Fix Python 3.9.1 build. Only tested on Mac OSX with Python 3.9.1.

Error Log:
```
> make -j2 install

No syscall32 to extract on your plateform
[  1%] Built target gen-syscall64
[  1%] Built target gen-syscall32
[  3%] Building CXX object src/libtriton/CMakeFiles/triton.dir/bindings/python/objects/pyAstContext.cpp.o
[  3%] Building CXX object src/libtriton/CMakeFiles/triton.dir/bindings/python/objects/pyAstNode.cpp.o
/Triton/src/libtriton/bindings/python/objects/pyAstNode.cpp:960:9: error: excess elements in struct initializer
        0,                                          /* bpo-37250: kept for backwards compatibility in CPython 3.8 only */
        ^
1 error generated.
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/bindings/python/objects/pyAstNode.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Triton/src/libtriton/bindings/python/objects/pyAstContext.cpp:1774:9: error: excess elements in struct initializer
        0,                                          /* bpo-37250: kept for backwards compatibility in CPython 3.8 only */
        ^
1 error generated.
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/bindings/python/objects/pyAstContext.cpp.o] Error 1
make[1]: *** [src/libtriton/CMakeFiles/triton.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
Hi,

Thanks for the MR. However, we patched this 14 days ago into the `dev-v0.9` branch. Can you tried to pull this branch and see if it's also working on OSX ?

Cheers,

**Comment by JonathanSalwan** [comment]
If it's working on your side, I will merge dev-v0.9 into master to avoid confusion.

**Comment by jakeloo** [comment]
Yup, `dev-0.9` works for me. Thanks!
