### PR TITLE
Fixed compile error and runtime problems

### PR DESCRIPTION
**Pull request by K-atc**
Hi, I have fixed following three issues:

1. [Compile Issue] Compile error in ArchLinux (gcc 8.1) and Ubuntu 16.04 (gcc 5.4)
2. [Runtime Issue] Pin tracer's signals handler misses SIGBUS
3. [Runtime Issue] Triton stops execution when z3::exception occurs

I checked if compilation successes in my following Linux.

Arch Linux (Latest):

```
K_atc% uname -r
4.17.2-1-ARCH
K_atc% gcc -v  
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.1 20180531 (GCC) 
```

Ubuntu 16.04:

```
tomori@nao:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
tomori@nao:~$ gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
```

### CODE REVIEW

File: src/libtriton/ast/z3/tritonToZ3Ast.cpp [hunk 1]
```diff
@@ -31,7 +31,11 @@ namespace triton {
         throw triton::exceptions::Exception("TritonToZ3Ast::getUintValue(): The ast is not a numerical value.");
 
       #if defined(__x86_64__) || defined(_M_X64)
-      Z3_get_numeral_uint64(this->context, expr, &result);
+          #if defined(__uint64)
+              Z3_get_numeral_uint64(this->context, expr, (__uint64*) &result);
+          #else
+              Z3_get_numeral_uint64(this->context, expr, (uint64_t*) &result);
+          #endif
```
Comment (JonathanSalwan) [inline src/libtriton/ast/z3/tritonToZ3Ast.cpp]: This is fixed into the `dev-v0.6`.

File: src/libtriton/bindings/python/objects/pyTritonContext.cpp [hunk 2]
```diff
@@ -1265,6 +1266,9 @@ namespace triton {
         catch (const triton::exceptions::Exception& e) {
           return PyErr_Format(PyExc_TypeError, "%s", e.what());
         }
+        catch (z3::exception e) {
+          std::cerr << "PyObject* TritonContext_getModel(): z3::exception: " << e.msg() << std::endl;
+        }
```
Comment (JonathanSalwan) [inline src/libtriton/bindings/python/objects/pyTritonContext.cpp]: I think it is better to add this exception into `z3Solver.cpp` instead of the bindings part.

**Comment by JonathanSalwan** [comment]
Can you also rebase your PR from `dev-v0.6` please.

File: src/libtriton/ast/z3/tritonToZ3Ast.cpp (hunk 1 above)
Comment (K-atc) [reply src/libtriton/ast/z3/tritonToZ3Ast.cpp]: I see. Thank you. I remove this commit.
https://github.com/JonathanSalwan/Triton/issues/679

File: src/libtriton/bindings/python/objects/pyTritonContext.cpp (hunk 2 above)
Comment (K-atc) [reply src/libtriton/bindings/python/objects/pyTritonContext.cpp]: I think so too. But, strange to say, I cannot catch z3::exception in SolverEngine.cpp (see attached patch file).
Is there any my mistake?

I also attached python script triggers z3::exception.

[handling-z3-exception-in-solverEngine-getModels.patch.txt](https://github.com/JonathanSalwan/Triton/files/2130928/handling-z3-exception-in-solverEngine-getModels.patch.txt)
[z3-exception.py.txt](https://github.com/JonathanSalwan/Triton/files/2130929/z3-exception.py.txt)

**Comment by K-atc** [comment]
@JonathanSalwan I've rebased my PR!

File: src/libtriton/CMakeLists.txt [hunk 3]
```diff
@@ -22,7 +22,8 @@ endif()
 # Global UNIX CXX Flags
 if(CMAKE_COMPILER_IS_GNUCXX OR ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
     # Flags
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Wno-unused-parameter -Wno-unknown-pragmas -Wno-mismatched-tags")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Wno-unused-parameter -Wno-unknown-pragmas")
+    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-mismatched-tags")
```
Comment (pbrunet) [inline src/libtriton/CMakeLists.txt]: What is the version of clang you are using? Because it is likely to break another clang configuration, isn't it?

Comment (K-atc) [reply src/libtriton/CMakeLists.txt]: Thanks for reviewing.
I did NOT tested my changes in clang.

`-Wno-mismatched-tags` is required for clang?
It seems `-Wno-mismatched-tags` is obsoleted in my gcc (Arch Linux, Ubuntu).

Comment (K-atc) [reply src/libtriton/CMakeLists.txt]: I tried compile my Triton with clang!
Here's my result.

### clang 6.0 (Arch Linux)
version info:

```
K_atc% clang --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I built [my Triton](https://github.com/K-atc/Triton/tree/dev-fix-errors) with clang 6.0.
I encountered following compile error.

```
In file included from /home/katc/project/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/bindings/python/init.cpp:8:
In file included from /home/katc/project/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/includes/triton/pythonBindings.hpp:11:
In file included from /usr/include/python2.7/Python.h:88:
/usr/include/python2.7/unicodeobject.h:534:5: error: 'register' storage class specifier is
      deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]
    register PyObject *obj,     /* Object */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:553:5: error: 'register' storage class specifier is
      deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]
    register PyObject *obj      /* Object */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:575:5: error: 'register' storage class specifier is
      deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]
    register const wchar_t *w,  /* wchar_t buffer */
    ^~~~~~~~~
/usr/include/python2.7/unicodeobject.h:593:5: error: 'register' storage class specifier is
      deprecated and incompatible with C++17 [-Werror,-Wdeprecated-register]
    register wchar_t *w,        /* wchar_t buffer */
    ^~~~~~~~~
```

It seems `-Wno-deprecated-register` is required.

### clang 3.8 (Ubuntu 16.04)
version info:
```
tomori@nao:~/bin/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build$ clang --version 
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I built [my Triton](https://github.com/K-atc/Triton/tree/dev-fix-errors) with clang 3.8.
I encountered following compile error.

```
/home/tomori/bin/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/includes/triton/registers_e.hpp:48:3: error: 
      'hash' defined as a class template here but previously declared as a struct template
      [-Werror,-Wmismatched-tags]
  class hash<triton::arch::registers_e>: public hash<uint64_t> {
```

It seems `-Wno-mismatched-tags` is required.

### Patch
Finally, I made following patch, and succeeded to compile in both clang 6.0 & 3.8.
(This patch is NOT applied to this pull request.)

```diff
diff --git a/src/libtriton/CMakeLists.txt b/src/libtriton/CMakeLists.txt
index 25acb8d6..037b1700 100644
--- a/src/libtriton/CMakeLists.txt
+++ b/src/libtriton/CMakeLists.txt
@@ -41,6 +41,12 @@ if(CMAKE_COMPILER_IS_GNUCXX OR ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
     if (CMAKE_COMPILER_IS_GNUCXX AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 8.1)
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=cast-function-type")
     endif()
+    if(${CMAKE_CXX_COMPILER_ID} MATCHES "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0) # Really?
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-mismatched-tags")
+    endif()
+    if(${CMAKE_CXX_COMPILER_ID} MATCHES "Clang" AND NOT(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0))
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-register")
+    endif()
 endif()
 
 # 32-bits
```

Comment (K-atc) [reply src/libtriton/CMakeLists.txt]: I got why Travis CI fails! I'll update my pullreq.

**Comment by JonathanSalwan** [comment]
I've merged your PR but I modified the way you caught z3's exception with this new commit 208d76ec.

**Comment by K-atc** [comment]
Thanks for merging and nice new commit!
